# -*- coding: utf-8 -*-
"""pre_trained_transformerssss.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vi-Fhwd8KCAZmEn8J-gUcT9abjj99yHj
"""

!pip install transformers sentencepiece -q

from transformers import pipeline

# Creating a Text2TextGenerationPipeline for language translation
pipe = pipeline(task='text2text-generation', model='facebook/m2m100_418M')

# Converting
pipe("That is a flower", forced_bos_token_id=pipe.tokenizer.get_lang_id(lang='hi'))# hi denotes hindi here!



# Converting
pipe("Hello", forced_bos_token_id=pipe.tokenizer.get_lang_id(lang='hi'))# hi denotes hindi here!

